### ISSUE TITLE
Тестирование на реальных ботах

### ISSUE THREAD

**Issue by NovelCoZ** [moevm/mse_duckietown_dashboard_WEB_Rviz#36]
В среду 11.05 в 12:30, ауд. 3501

Результатом работы д.б. видеоотчет, залить на yandex.disk, в обсуждении оставить ссылку.

Задача для всех, ответственный - Дмитрий

**Comment by lastrise** [comment]
https://disk.yandex.ru/d/9Z4HRsdGyzkBUg
