### ISSUE TITLE
Ручное тестирование приложения

### ISSUE THREAD

**Issue by NovelCoZ** [moevm/mse_duckietown_dashboard_WEB_Rviz#37]
С нуля в соответствии с инструкцией установить и запустить проект, проверить корректность инструкции.

Протестировать локально функционал, описанный в документации пользователя. Нужно убедиться, что все работает корректно, и приложение не падает, если данные были введены некорректно.

**Comment by Kirill-Mois** [comment]
"5. Зарегистрироваться на https://www.duckietown.org/, получить индивидуальный токен для входа в приложение" - этот шаг нигде дальше не упоминается

**Comment by Kirill-Mois** [comment]
"! В инструкции не указаны дальнейшие действия по установке Foxglove Studio." - дальнейшие действия после установки /compose/:
1. docker pull whitecurl/foxglove:latest
2. Запустить контейнер
![Screenshot from 2022-05-31 19-31-32](https://user-images.githubusercontent.com/55047341/171226756-2dd663fb-2155-4224-9aeb-06c8b3b3211f.png)
3. В Docker Desktop перейти во вкладку Containers и открыть CLI терминал контейнера afdaniele/compose
В терминале контейнера:
4. cd /user-data
5. mkdir packages
6. cd packages
7. git clone https://github.com/moevm/mse_duckietown_dashboard_WEB_Rviz
8. mv mse_duckietown_dashboard_WEB_Rviz ./webviz
9. Перейти в браузере на localhost:8080
10. В /compose/ зайти во вкладку Settings >> Package: webviz
11. Установить Webviz port: 80

Примечание: пункты 10, 11 можно опустить, если изначально установить контейнер webviz на порт 8080, а контейнер compose на другой порт, например, 80, но для этого нужно поменять инструкцию, сделать новые скриншоты Docker Desktop с нужными портами и поменять в инструкции ссылки localhost

**Comment by NovelCoZ** [comment]
Ссылку на foxglove поменять на форк дмитрия

![image](https://user-images.githubusercontent.com/31564067/171960309-d984daaf-ed32-4dfb-bb47-ac8e44c08d2b.png)

**Comment by NovelCoZ** [comment]
"Сначала нужно собрать образы... для этого нужно запустить контейнер..." - неправильно

![image](https://user-images.githubusercontent.com/31564067/171960501-a2899f02-8281-4b65-8711-0e5ef88b3613.png)

**Comment by NovelCoZ** [comment]
\сompose\

![image](https://user-images.githubusercontent.com/31564067/171960655-b38d4bde-2f4a-4575-becc-1cad45d953e8.png)

**Comment by NovelCoZ** [comment]
Добавить картинку, куда drag-and-drop делать. "При работе с проектом через систему \compose\ диалоговое окно открытия файла не открывается. Вместо использования данной кнопки необходимо воспользоваться drag-and-drop"

![image](https://user-images.githubusercontent.com/31564067/171960751-7821c7fb-e45c-47ff-990d-ce3aeaa672dc.png)

**Comment by Kirill-Mois** [comment]
Ручное тестирование приложения:

Кнопка import layout -- выдается ошибка TypeError: window.showOpenFilePicker is not a function

![Screenshot from 2022-06-04 18-23-14](https://user-images.githubusercontent.com/55047341/172012194-82e5342c-beb3-4cf1-8e0b-ffd66437f138.png)

Кнопка Sign in -- не открывается ссылка console.foxglove.dev

![Screenshot from 2022-06-04 18-23-25](https://user-images.githubusercontent.com/55047341/172012216-f027532a-f41d-4bfd-9360-2fa3f491aa38.png)
![Screenshot from 2022-06-04 18-31-32](https://user-images.githubusercontent.com/55047341/172012397-d8010f8c-0418-4285-ac94-9d595e70cdfd.png)
