### ISSUE TITLE
Работа на ARM

### ISSUE THREAD

**Issue by NovelCoZ** [moevm/mse_duckietown_dashboard_WEB_Rviz#43]
Разобраться, какие пакеты, используемые foxglove, не совместимы с ARM, и можем ли мы в обозримые сроки заставить работать визуализатор на данной архитектуре.

**Comment by lastrise** [comment]
Собрал Docker образ для ARM64 и AMD64

https://hub.docker.com/r/whitecurl/foxglove/tags
